/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 35adec2698b59f69b8a41fe11c31e843)
interface __BaseEnv_Env {
	DB: D1Database;
	DIGEST_QUEUE: Queue;
	HEALTHCHECK_URL: "https://hc-ping.com/00000000-0000-0000-0000-000000000000";
	DIGEST_FROM_ADDRESS: "digest@pawster.dpdns.org";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "HEALTHCHECK_URL" | "DIGEST_FROM_ADDRESS">> {}
}
