/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=./test/fixture/wrangler.jsonc --include-runtime=false ./worker-configuration.d.ts` (hash: 430a4ee8fdad5896c55a451a5c680f49)
interface __BaseEnv_Env {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./test/fixture/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
