#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# Braces wrap the whole script so bash parses it to the closing brace before it
# runs a single line. Without them bash reads the file lazily, by byte offset:
# edit the wizard while a human is running it and the live process resumes at a
# now-meaningless position, dying with a syntax error the file does not contain.
# Observed on 2026-09-03, mid-stage-6.
{

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Pawster's free domain — issue #18, ADR 0014.
#
# scripts/provision.sh provisions the stack. This wizard provisions the one
# thing it deliberately left out: a domain.
#
# ADR 0014 decides three things that shape every stage below.
#
#   1. Pawster buys nothing. The domain is a free subdomain of a suffix on the
#      Public Suffix List.
#   2. It is NOT added to Cloudflare. Cloudflare Trust & Safety has suspended
#      accounts over this suffix, and a suspended account would take R2, D1,
#      Queues and Workers with it. The domain is delegated to deSEC instead,
#      so Pawster's Cloudflare account never learns the suffix exists.
#   3. Therefore there is no R2 custom domain, now or later. Images stay on
#      r2.dev until a cached Worker replaces it. The domain exists for ONE
#      reason: so Resend can verify a sending domain and the digest can reach
#      somebody other than you.
#
# Read that third point twice before adding a stage here. Every temptation to
# "just point the images at it too" is the thing ADR 0014 rejected.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "Pawster: the free domain, and its DNS outside Cloudflare"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools the later stages shell out to."
MISSING=""
for _t in dig gh; do
  if command -v "$_t" >/dev/null 2>&1; then
    step "$_t — found"
  else
    step "$_t — MISSING"
    MISSING="$MISSING $_t"
  fi
done
if [[ -n "$MISSING" ]]; then
  printf '\n'
  warn "missing:$MISSING — install them before continuing."
  note "dig is used to prove the delegation is live; gh writes the CI secret."
  confirm "Continue anyway?" || exit 1
fi
printf '\n'
if [[ -f "$ENV_FILE" ]]; then
  step "$ENV_FILE found — existing values will be offered as defaults."
else
  warn "no $ENV_FILE here. Run scripts/provision.sh first: this wizard adds the"
  warn "domain to an already-provisioned stack, it does not replace it."
  confirm "Continue anyway?" || exit 1
fi
pause "Press Enter to continue."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Register the free domain"
say "DigitalPlat FreeDomain issues subdomains of dpdns.org at no cost, with no"
say "card and no renewal fee. Cloudflare's own test for admitting a zone is"
say "Public Suffix List membership, and dpdns.org has been on the list since"
say "March 2025 — which is why this works where most free-subdomain services"
say "do not."
printf '\n'
note "Eligibility is a GitHub account of some age. If you are refused, the"
note "fallback is stage 7's eu.org application, which is free but slow."
printf '\n'
open_url "https://domain.digitalplat.org/"
step "Sign in with GitHub and register 'pawster' under dpdns.org."
step "Do NOT choose Cloudflare when it offers you a nameserver. Stage 3"
step "explains why; you will paste deSEC's nameservers in stage 4."
ask PAWSTER_DOMAIN "Domain you registered (e.g. pawster.dpdns.org):"
# Bounded, not `while [[ -z ]]`: on EOF `ask` returns empty forever, so an
# unbounded retry would spin silently when this is piped rather than typed.
for _try in 1 2 3; do
  [[ -n "$PAWSTER_DOMAIN" ]] && break
  warn "every stage after this one interpolates the domain, so an empty value"
  warn "would quietly produce nonsense instructions. It is required."
  ask PAWSTER_DOMAIN "Domain you registered (e.g. pawster.dpdns.org):"
done
if [[ -z "$PAWSTER_DOMAIN" ]]; then
  warn "no domain given. Register one first, then re-run; nothing is lost."
  exit 1
fi
write_env PAWSTER_DOMAIN "$PAWSTER_DOMAIN"
pause "Press Enter to continue."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Why this domain must not touch Cloudflare"
warn "Read this one before doing anything. It is the whole reason the next"
warn "stage exists, and it is easy to undo by accident."
printf '\n'
say "Adding $PAWSTER_DOMAIN to Cloudflare would work. It would also restore"
say "the R2 custom domain, which is genuinely tempting."
printf '\n'
warn "Cloudflare Trust & Safety has suspended ACCOUNTS over *.dpdns.org during"
warn "2025-26, and PSL maintainers recorded VirusTotal malicious detections"
warn "across all four DigitalPlat suffixes. A suspended domain is a nuisance."
warn "A suspended account takes R2, D1, Queues and Workers with it."
printf '\n'
note "ADR 0006 deliberately put the whole platform on one vendor. Attaching a"
note "shared-abuse suffix to that account aims a tail risk squarely at the"
note "single point of failure the project already accepted."
printf '\n'
say "It costs nothing to avoid, because images no longer need the zone:"
say "Workers Cache is zone-independent and caches on workers.dev, so the chain"
say "that made a custom domain load-bearing (ADR 0011) no longer holds."
printf '\n'
if confirm "Understood — this domain will never be added to Cloudflare?"; then
  step "good. Stage 4 delegates it to deSEC instead."
else
  warn "Stopping. Re-read ADR 0014 before continuing; if you disagree with it,"
  warn "amend the ADR rather than diverging from it silently."
  exit 1
fi
pause "Press Enter to continue."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Delegate it to deSEC"
say "DigitalPlat provides no DNS record editor at all — delegation to an"
say "external nameserver is its only mode. So we need a nameserver regardless;"
say "the only choice is which, and choosing not-Cloudflare is free."
printf '\n'
say "deSEC is a free, non-profit, DNSSEC-by-default DNS host, and DigitalPlat's"
say "own tutorial names it as a supported option."
printf '\n'
open_url "https://desec.io/"
step "Create an account and add '$PAWSTER_DOMAIN' as a domain."
step "deSEC will show you its nameservers (ns1.desec.io and ns2.desec.org)."
printf '\n'
open_url "https://domain.digitalplat.org/"
step "Back at DigitalPlat, set $PAWSTER_DOMAIN's nameservers to those two."
pause "Press Enter once you have saved the nameservers."
printf '\n'
say "Checking the delegation is actually live:"
NS_OUT=$(dig +short NS "$PAWSTER_DOMAIN" 2>/dev/null || true)
NS_LOWER=$(printf '%s' "$NS_OUT" | tr '[:upper:]' '[:lower:]')
if [[ -z "$NS_OUT" ]]; then
  warn "no NS records answered yet."
  note "DigitalPlat's registry is known to publish delegations slowly and"
  note "sometimes intermittently — reports put it at up to ~48 hours. This is"
  note "expected, not a mistake. Re-run this wizard later; nothing is lost."
  SKIPPED+=("re-check: dig +short NS $PAWSTER_DOMAIN should return desec.io/desec.org")
elif [[ "$NS_LOWER" == *desec* ]]; then
  printf '%s\n' "$NS_OUT" | sed 's/^/    /'
  step "nameservers are deSEC — delegation confirmed."
elif [[ "$NS_LOWER" == *ns.cloudflare.com* ]]; then
  printf '%s\n' "$NS_OUT" | sed 's/^/    /'
  warn "these are CLOUDFLARE nameservers. That is exactly what stage 3 rules"
  warn "out. Remove the zone from your Cloudflare account and re-delegate to"
  warn "deSEC before continuing."
  SKIPPED+=("URGENT: $PAWSTER_DOMAIN is delegated to Cloudflare, against ADR 0014")
else
  printf '%s\n' "$NS_OUT" | sed 's/^/    /'
  warn "those are neither deSEC nor Cloudflare. Resend verification in stage 6"
  warn "will fail until the records live where you can edit them."
  SKIPPED+=("delegate $PAWSTER_DOMAIN to deSEC")
fi
pause "Press Enter to continue."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Resend: the sending subdomain"
say "Resend recommends sending from a subdomain rather than the root, to keep"
say "the sending reputation isolated: 'We recommend sending your emails from"
say "one or more subdomains (e.g., updates.example.com) instead of your root"
say "domain to isolate your sending reputation.'"
printf '\n'
RESEND_SENDING_DOMAIN="mail.$PAWSTER_DOMAIN"
say "So the sending domain is: $RESEND_SENDING_DOMAIN"
write_env RESEND_SENDING_DOMAIN "$RESEND_SENDING_DOMAIN"
printf '\n'
open_url "https://resend.com/domains"
step "Add Domain → $RESEND_SENDING_DOMAIN → pick the region closest to you."
step "Resend will show you the DNS records it wants. Leave the page open."
printf '\n'
warn "Expect CNAMEs, not MX and TXT. Resend's docs hedge — 'for domains created"
warn "after August 2026, Resend may generate CNAME records instead' — but this"
warn "was observed first-hand on 2026-09-03, and CNAMEs are what it issued."
note "That matters because a CNAME is the one record type that cannot share a"
note "name with anything else, which is what stage 6 is about. Copy whatever it"
note "actually shows you, not what an older doc or ADR describes."
pause "Press Enter once Resend has shown you the records."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Resend: publish the records at deSEC, and verify"
open_url "https://desec.io/domains"
step "Open $PAWSTER_DOMAIN at deSEC and add every record Resend listed."
printf '\n'
note "deSEC groups records into record sets by name and type, so add each"
note "Resend row as its own set. There is no proxying to disable here — that"
note "was a Cloudflare hazard, and we are deliberately not on Cloudflare."
printf '\n'
warn "The Subname field is where this goes wrong, and it has gone wrong before."
say "deSEC asks for a SUBNAME, but Resend shows you a FULL record name. The"
say "subname is the full name with the domain stripped off the end:"
printf '\n'
note "  Resend shows:  resend._domainkey.$RESEND_SENDING_DOMAIN"
note "  deSEC wants:   resend._domainkey.mail"
printf '\n'
note "  Resend shows:  send.$RESEND_SENDING_DOMAIN"
note "  deSEC wants:   send.mail"
printf '\n'
warn "Strip the WHOLE domain, not just the public suffix. Observed 2026-09-03:"
warn "stripping only '.${PAWSTER_DOMAIN#*.}' leaves the '${PAWSTER_DOMAIN%%.*}' behind, and"
warn "deSEC appends the zone again, so the record lands at"
note "  resend._domainkey.mail.${PAWSTER_DOMAIN%%.*}.$PAWSTER_DOMAIN"
warn "which resolves perfectly and is not the name Resend looks up. Nothing"
warn "errors; verification just never goes green. The check below catches it."
printf '\n'
warn "It is NEVER blank. Leaving it blank aims the record at the zone apex,"
warn "and if the record is a CNAME you will get:"
note "  'RRset with conflicting type present at same subname: (NS, TXT).'"
note "  '(No other RRsets are allowed alongside CNAME.)'"
printf '\n'
note "That is DNS refusing you, not deSEC being fussy: the apex must hold SOA"
note "and NS to be a zone at all, and a CNAME is only legal at a name holding"
note "nothing else. There is no override. Fill in the subname and it goes away."
printf '\n'
note "Keep the 'mail' in it. ADR 0014 sends from a subdomain, so every Resend"
note "record sits under mail — which is also why none of them can ever collide"
note "with the apex once the subname is right."
printf '\n'
warn "Copy the target values by paste, not by eye — one wrong character fails"
warn "verification with no useful error."
note "Do not 'correct' a target that reads 'rsend.forge.rmta.net'. It looks like"
note "a typo for 'resend.' and is not: both hostnames are live Resend"
note "infrastructure, carrying different SPF. Publish exactly what you are shown."
printf '\n'
say "Checking what actually resolves before you click Verify."
_dns_bad=""
for _n in "resend._domainkey.$RESEND_SENDING_DOMAIN" "send.$RESEND_SENDING_DOMAIN"; do
  _got=$( { dig +short TXT "$_n"; dig +short CNAME "$_n"; } 2>/dev/null | head -1 )
  if [[ -n "$_got" ]]; then
    step "$_n resolves."
    continue
  fi
  _dns_bad=1
  _doubled="${_n%.$PAWSTER_DOMAIN}.${PAWSTER_DOMAIN%%.*}.$PAWSTER_DOMAIN"
  if [[ -n "$( { dig +short TXT "$_doubled"; dig +short CNAME "$_doubled"; } 2>/dev/null | head -1 )" ]]; then
    warn "$_n does not resolve — but $_doubled does."
    warn "That is the doubled label above. Edit the subname in deSEC to drop the"
    warn "extra '${PAWSTER_DOMAIN%%.*}', then re-run this stage."
  else
    warn "$_n does not resolve yet. Either it is not published, or deSEC has not"
    warn "caught up. Re-check before clicking Verify."
  fi
done
if [[ -n "$_dns_bad" ]]; then
  SKIPPED+=("deSEC: at least one Resend record does not resolve at the name Resend looks up")
fi
printf '\n'
step "Back at Resend, click Verify."
printf '\n'
warn "DNS propagation is minutes, not hours, at deSEC — but Resend polls on"
warn "its own schedule. If it does not go green immediately, wait and re-check"
warn "rather than re-adding the records."
ask RESEND_DOMAIN_STATUS "Domain status in Resend (verified / pending / failed):"
write_env RESEND_DOMAIN_STATUS "$RESEND_DOMAIN_STATUS"
if [[ "$(printf '%s' "$RESEND_DOMAIN_STATUS" | tr '[:upper:]' '[:lower:]')" != verified* ]]; then
  SKIPPED+=("Resend: verify $RESEND_SENDING_DOMAIN (currently: $RESEND_DOMAIN_STATUS)")
fi
printf '\n'
say "One observation to make now rather than after the first real digest:"
warn "Google Postmaster Tools reports on 'primary domains only, not to"
warn "subdomains', and never defines 'primary domain' or mentions the Public"
warn "Suffix List. Whether Google scores you as $PAWSTER_DOMAIN or as the whole"
warn "of dpdns.org cannot be determined from any public source — and it is the"
warn "single unknown that decides whether this domain was a good idea."
printf '\n'
open_url "https://postmaster.google.com/"
step "Enrol $RESEND_SENDING_DOMAIN, then check which domain it reports under."
ask GPT_REPORTS_UNDER "What domain does Postmaster Tools report under? (or 'not yet'):"
write_env GPT_REPORTS_UNDER "$GPT_REPORTS_UNDER"
pause "Press Enter to continue."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Lodge the eu.org application as a hedge"
say "eu.org issues free subdomains too, has done since 1996, and reviews every"
say "application by hand — which is why its abuse neighbourhood is cleaner than"
say "dpdns.org's, and why it takes one to three months to hear back."
printf '\n'
note "Nothing waits on this. If it is granted, it is a drop-in replacement:"
note "re-verify the Resend subdomain against it and change one env value. If it"
note "never arrives, you have lost a form."
printf '\n'
warn "Do NOT wait for it before shipping. Year-old applications are still"
warn "unapproved, and stage 2's domain already works today."
printf '\n'
open_url "https://nic.eu.org/"
step "Create an account and apply for 'pawster.eu.org'."
step "When it asks for nameservers, give deSEC's — the same two as stage 4."
ask EU_ORG_APPLIED "Applied? (yes / no / refused):"
write_env EU_ORG_APPLIED "$EU_ORG_APPLIED"
if [[ "$(printf '%s' "$EU_ORG_APPLIED" | tr '[:upper:]' '[:lower:]')" != yes* ]]; then
  SKIPPED+=("eu.org application for pawster.eu.org (the free hedge)")
fi
pause "Press Enter to finish."

finish
printf '  %sWhat changed for the rest of the project%s\n\n' "$BOLD" "$RESET"
note "  - The digest can now reach real subscribers, not just you. That was the"
note "    one thing the domain was blocking."
note "  - Images are unaffected: still r2.dev, still no custom domain, and"
note "    still nothing to change until a cached Worker replaces it."
note "  - Cloudflare still holds no zone for Pawster. Keep it that way."
printf '\n'
note "Update docs/provisioning-record.md with $PAWSTER_DOMAIN and the Resend"
note "status, then paste it onto issue #18 if it is still open."
printf '\n'

}
