#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Pawster stack provisioning — issue #18.
#
# Every step below is a registrar, dashboard or CLI action that only a human
# with the accounts can take. The wizard opens each page, says what to click,
# captures the facts later tickets depend on, and writes a provisioning record
# you can paste onto the ticket as its resolution.
# ──────────────────────────────────────────────────────────────────────────

# ── Modes ─────────────────────────────────────────────────────────────────
# --no-domain provisions everything that does not need a domain, for the
# prototype phase ADR 0014 describes.
NO_DOMAIN=0

usage() {
  cat <<'USAGE'
Usage: scripts/provision.sh [--no-domain]

  --no-domain   Skip every stage that needs a domain and its Cloudflare zone
                (the domain itself, the zone id, Images transformations, and
                both Resend DNS stages), and serve R2 from its auto-generated
                r2.dev hostname instead of a custom domain.

                Sending email to anyone other than this account own address
                is NOT possible in this mode: Resend domain verification needs
                DNS records that a hosting free-tier hostname cannot publish.
                See docs/adr/0014-domain-free-prototype-phase.md.

  -h, --help    Show this message.

Re-running is safe: values already in .env are offered as defaults.
USAGE
}

for _arg in "$@"; do
  case "$_arg" in
    --no-domain) NO_DOMAIN=1 ;;
    -h|--help)   usage; exit 0 ;;
    *) printf 'provision.sh: unknown option %s\n\n' "$_arg" >&2; usage >&2; exit 2 ;;
  esac
done

if (( NO_DOMAIN )); then
  TOTAL_STAGES=17
  # Stages 2, 10, 13 and 14 never run, so the facts they would have captured
  # are defined empty here: under `set -u` the stage 21 record would abort.
  PAWSTER_DOMAIN=""
  CLOUDFLARE_ZONE_ID=""
  IMAGES_TRANSFORMATIONS_ON_FREE="not observed - no zone in this phase"
  RESEND_SENDING_DOMAIN=""
  RESEND_DOMAIN_STATUS="sandbox only - onboarding@resend.dev"
else
  TOTAL_STAGES=21
fi
RECORD="docs/provisioning-record.md"

# Suppress wrangler's first-run telemetry question: it is interactive, and a
# prompt raised inside capture() would be invisible and hang the wizard.
export WRANGLER_SEND_METRICS=false

# wr runs wrangler: a binary on PATH if there is one, else the npx download.
wr() {
  if command -v wrangler >/dev/null 2>&1; then wrangler "$@"
  else npx --yes wrangler "$@"; fi
}

# capture runs a command, indents its output for the human, and leaves the
# text in $CAPTURED so a stage can grep an id out of what just scrolled past.
CAPTURED=""
capture() {
  local tmp rc=0
  tmp=$(mktemp)
  "$@" >"$tmp" 2>&1 || rc=$?
  sed 's/^/    /' "$tmp"
  CAPTURED=$(cat "$tmp")
  rm -f "$tmp"
  return "$rc"
}

if (( NO_DOMAIN )); then
  banner "Pawster: provision the stack - domain-free prototype phase"
else
  banner "Pawster: provision the stack accounts and the domain"
fi

# The notice sits after banner() and ends with its own pause, because stage()
# clears the screen: printed any earlier it would be wiped before it is read.
if (( NO_DOMAIN )); then
  printf '\n%s%s  Domain-free prototype phase%s\n\n' "$BOLD" "$YELLOW" "$RESET"
  warn "Four stages need a domain and its Cloudflare zone. They are skipped,"
  warn "and the r2.dev hostname is substituted for the custom domain. Numbered"
  warn "as they would be in a full run, the four are:"
  note "   2  the domain, and its zone on Cloudflare"
  note "  10  Images transformations (observation only; needs a zone)"
  note "  13  the Resend sending subdomain"
  note "  14  the Resend DNS records (MX, SPF, DKIM)"
  printf '\n'
  warn "The consequence, stated plainly: Resend can only send to this account"
  warn "own address, because domain verification needs DNS records that this"
  warn "phase has nowhere to publish. Shelter sign-in codes (ADR 0013), admin"
  warn "verification links (ADR 0002) and the subscriber digest (ADR 0009)"
  warn "therefore work for you alone. Onboarding a second shelter, or one real"
  warn "subscriber, requires a domain. No hosting free tier substitutes."
  printf '\n'
  note "The reasoning is recorded in docs/adr/0014-domain-free-prototype-phase.md."
  pause "Press Enter to acknowledge and begin."
fi

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight: tools, and keeping .env out of version control"
say "Checking the handful of tools the later stages shell out to."
MISSING=""
for _t in openssl dig node npx gh; do
  if command -v "$_t" >/dev/null 2>&1; then
    step "$_t — found"
  else
    step "$_t — MISSING"
    MISSING="$MISSING $_t"
  fi
done
if [[ -n "$MISSING" ]]; then
  warn "install these before continuing:$MISSING"
  exit 1
fi
if gh auth status >/dev/null 2>&1; then
  step "gh — authenticated"
else
  warn "gh is not authenticated. Run 'gh auth login' in another terminal, then re-run."
  exit 1
fi
printf '\n'
say "This wizard writes secrets to $ENV_FILE, which must never be committed."
IGNORE_FILE=".gitignore"
for _pat in '.env' '.env.*' '!.env.example' '.dev.vars' 'node_modules/' '.wrangler/'; do
  if [[ -f "$IGNORE_FILE" ]] && grep -qxF "$_pat" "$IGNORE_FILE"; then
    note "ignore rule already present: $_pat"
  else
    printf '%s\n' "$_pat" >> "$IGNORE_FILE"
    step "added ignore rule: $_pat"
  fi
done
printf '\n'
if (( NO_DOMAIN )); then
  warn "Nothing has been bought or created yet, and nothing in this run costs"
  warn "money: the one stage that spends any is the domain, which is skipped."
else
  warn "Nothing has been bought or created yet. Stage 2 is the one that costs money."
fi
pause "Press Enter to continue."

# ── 2 ─────────────────────────────────────────────────────────────────────
if (( ! NO_DOMAIN )); then
  stage "The domain, and its zone on Cloudflare"
  say "The domain comes first because everything hangs off it: R2 must serve"
  say "images from a custom domain, and a custom domain requires the zone to sit"
  say "in the same Cloudflare account as the bucket."
  printf '\n'
  warn "The zone must be a FULL setup — nameservers delegated to Cloudflare."
  note "A partial (CNAME) setup would avoid moving nameservers, but Cloudflare's"
  note "docs restrict it: 'A CNAME setup (partial) is only available to customers"
  note "on a Business or Enterprise plan.' Free and Pro are listed as No, so for"
  note "a \$0 project full setup is the only route. This corrects"
  note "docs/research/free-tier-image-storage.md, which reads the other way."
  printf '\n'
  say "Easiest path: register at Cloudflare Registrar, which sells at wholesale"
  say "cost and creates the zone as a full setup for you. Registering elsewhere is"
  say "fine — you then repoint the nameservers by hand at that registrar."
  open_url "https://dash.cloudflare.com/?to=/:account/domains/register"
  step "Register the domain (or 'Add a site' if you bought it elsewhere)."
  step "Follow it through until the zone shows Active."
  ask PAWSTER_DOMAIN "Domain you registered (e.g. pawster.org):"
  write_env PAWSTER_DOMAIN "$PAWSTER_DOMAIN"
  printf '\n'
  say "Checking the delegation actually points at Cloudflare:"
  NS_OUT=$(dig +short NS "$PAWSTER_DOMAIN" 2>/dev/null || true)
  if [[ -z "$NS_OUT" ]]; then
    warn "no NS records answered yet — delegation can take a few hours."
    SKIPPED+=("re-check: dig +short NS $PAWSTER_DOMAIN should return *.ns.cloudflare.com")
  elif [[ "$(printf '%s' "$NS_OUT" | tr '[:upper:]' '[:lower:]')" == *ns.cloudflare.com* ]]; then
    printf '%s\n' "$NS_OUT" | sed 's/^/    /'
    step "nameservers are Cloudflare — full setup confirmed."
  else
    printf '%s\n' "$NS_OUT" | sed 's/^/    /'
    warn "those are not Cloudflare nameservers. R2's custom domain will not"
    warn "attach until they are. Fix the delegation before stage 6."
    SKIPPED+=("delegate $PAWSTER_DOMAIN nameservers to Cloudflare (full setup)")
  fi
  pause "Press Enter to continue."
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
if (( NO_DOMAIN )); then
  stage "Cloudflare: confirm Workers Free, capture the account id"
else
  stage "Cloudflare: confirm Workers Free, capture account and zone ids"
fi
say "We stay on Workers Free. The \$5/month Workers Paid plan is ADR 0006's"
say "named escape hatch, not the baseline — do not subscribe to it now."
open_url "https://dash.cloudflare.com/?to=/:account/workers/plans"
step "Confirm the account is on the Free plan. Do not upgrade."
pause "Press Enter once confirmed."
printf '\n'
say "Logging wrangler in so later stages can create resources from the CLI."
if wr whoami >/dev/null 2>&1; then
  note "wrangler is already logged in."
else
  wr login || warn "wrangler login did not complete; run it by hand and re-run."
fi
capture wr whoami || true
CF_ACCOUNT_GUESS=$(printf '%s\n' "$CAPTURED" | grep -oE '[0-9a-f]{32}' | head -n1 || true)
if [[ -n "$CF_ACCOUNT_GUESS" ]]; then
  step "detected account id: $CF_ACCOUNT_GUESS"
  CLOUDFLARE_ACCOUNT_ID="$CF_ACCOUNT_GUESS"
  write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
else
  ask CLOUDFLARE_ACCOUNT_ID "Paste the Account ID (32 hex characters):"
  write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
fi
if (( NO_DOMAIN )); then
  printf '\n'
  note "Skipping the Zone ID: this phase has no zone, and the stage that needed"
  note "it - attaching the R2 custom domain - is substituted by the r2.dev"
  note "stage that follows the bucket."
  pause "Press Enter to continue."
else
  printf '\n'
  say "The Zone ID is what stage 6 needs to attach R2's custom domain."
  open_url "https://dash.cloudflare.com/?to=/:account/$PAWSTER_DOMAIN"
  step "On the domain's Overview page, find 'API' low in the right sidebar and"
  step "copy the Zone ID."
  ask CLOUDFLARE_ZONE_ID "Paste the Zone ID (32 hex characters):"
  write_env CLOUDFLARE_ZONE_ID "$CLOUDFLARE_ZONE_ID"
  pause "Press Enter to continue."
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Activate R2 — and settle the card question"
say "R2 activation runs a checkout flow. Cloudflare's docs say only 'complete"
say "the checkout flow' and never state whether card details are required."
say "Issue #12 left this unobserved; it gates nothing, but it decides whether"
say "the budget-alert stage below is even available, so record what happens."
open_url "https://dash.cloudflare.com/?to=/:account/r2/overview"
step "Click through to enable R2 on this account."
printf '\n'
ask R2_ACTIVATION_ASKED_FOR_CARD "Did activation demand card details? (yes / no / notes):"
write_env R2_ACTIVATION_ASKED_FOR_CARD "$R2_ACTIVATION_ASKED_FOR_CARD"
printf '\n'
note "R2's free allowance, for the record: 10 GB-month storage, 1M Class A"
note "operations, 10M Class B operations, egress free. Standard storage only —"
note "the allowance does not apply to Infrequent Access."
pause "Press Enter to continue."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Create the R2 bucket"
say "One bucket holds every animal photo derivative and the compact JSON filter"
say "index the listing is filtered from in the browser (ADR 0007)."
ask R2_BUCKET "Bucket name [Enter for pawster-media]:"
[[ -z "$R2_BUCKET" ]] && R2_BUCKET="pawster-media"
write_env R2_BUCKET "$R2_BUCKET"
printf '\n'
if capture wr r2 bucket create "$R2_BUCKET"; then
  step "bucket created."
else
  warn "create failed. If it says the bucket already exists, that is fine."
fi
pause "Press Enter to continue."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "The originals bucket, and its 7-day lifecycle rule"
say "ADR 0012 keeps every uploaded original for 7 days in a bucket of its own,"
say "then expires it. That window is what turns a pipeline bug — a bad crop, a"
say "broken encoder — from irreversible into recoverable: the 1280px derivative"
say "is otherwise the master, and nothing larger can ever be backfilled."
printf '\n'
warn "This bucket must NEVER be public and must never get a custom domain."
warn "Derivatives are clean by default — WebP output discards metadata"
warn "unconditionally — but a retained original is not. A volunteer"
warn "photographing a foster animal indoors embeds that home's coordinates."
printf '\n'
ask R2_ORIGINALS_BUCKET "Originals bucket name [Enter for pawster-originals]:"
[[ -z "$R2_ORIGINALS_BUCKET" ]] && R2_ORIGINALS_BUCKET="pawster-originals"
write_env R2_ORIGINALS_BUCKET "$R2_ORIGINALS_BUCKET"
printf '\n'
if capture wr r2 bucket create "$R2_ORIGINALS_BUCKET"; then
  step "bucket created."
else
  warn "create failed. If it says the bucket already exists, that is fine."
fi
printf '\n'
say "Adding the expiry rule. Cloudflare expires marked objects 'typically"
say "within 24 hours', so 7 days is a floor rather than a guarantee."
R2_ORIGINALS_LIFECYCLE="not set"
if capture wr r2 bucket lifecycle add "$R2_ORIGINALS_BUCKET" \
     expire-originals-7d "" --expire-days 7 --force; then
  step "lifecycle rule 'expire-originals-7d' added."
  R2_ORIGINALS_LIFECYCLE="expire-originals-7d — 7 days, all prefixes"
else
  warn "the CLI could not add it. Do it in the dashboard instead:"
  note "R2 -> $R2_ORIGINALS_BUCKET -> Settings -> Object lifecycle rules -> Add"
  note "a rule applying to all objects that deletes them 7 days after upload."
  open_url "https://dash.cloudflare.com/?to=/:account/r2/default/buckets/$R2_ORIGINALS_BUCKET/settings"
  pause "Press Enter once the rule is listed."
  R2_ORIGINALS_LIFECYCLE="added by hand in the dashboard"
fi
write_env R2_ORIGINALS_LIFECYCLE "$R2_ORIGINALS_LIFECYCLE"
printf '\n'
warn "Do NOT attach a custom domain or enable r2.dev on this bucket."
note "ADR 0012 also leans on this rule to collect abandoned upload sessions,"
note "'so neither needs code' in ADR 0010's daily purge. It plainly collects an"
note "abandoned session's originals. Whether a staged derivative stranded in"
note "$R2_BUCKET is swept by the same reasoning is not settled by the ADR —"
note "raise it with whoever builds the upload path."
pause "Press Enter to continue."

# ── 7 ─────────────────────────────────────────────────────────────────────
if (( NO_DOMAIN )); then
  stage "Serve the bucket from its r2.dev hostname"
  say "Without a zone there is no custom domain, so the bucket is served from"
  say "the hostname Cloudflare generates for it: pub-<hash>.r2.dev."
  printf '\n'
  warn "This is the trade ADR 0014 records. r2.dev is not CDN-cached, so an"
  warn "image view is a billable Class B GetObject instead of an edge hit, and"
  warn "the hostname carries a variable rate limit Cloudflare does not publish."
  printf '\n'
  note "Why it is affordable anyway: the free allowance is 10M Class B ops per"
  note "month, and the image-storage research puts a lean session at ~28 image"
  note "requests, so reads do not bind until ~357,000 sessions/month - and that"
  note "figure already assumes zero cache hits. This costs the growth phase,"
  note "not the prototype."
  printf '\n'
  say "Enabling the dev URL by CLI. Passing -y because capture() hides a"
  say "confirmation prompt, which would hang the wizard invisibly."
  if capture wr r2 bucket dev-url enable "$R2_BUCKET" -y; then
    step "public dev URL enabled."
  else
    warn "the CLI could not enable it. Do it in the dashboard instead:"
    note "R2 -> $R2_BUCKET -> Settings -> Public Development URL -> Allow"
    open_url "https://dash.cloudflare.com/?to=/:account/r2/default/buckets/$R2_BUCKET/settings"
    pause "Press Enter once the dev URL is showing as enabled."
  fi
  capture wr r2 bucket dev-url get "$R2_BUCKET" || true
  R2_HOST_GUESS=$(printf '%s\n' "$CAPTURED" | grep -oE 'pub-[0-9a-z]+\.r2\.dev' | head -n1 || true)
  if [[ -n "$R2_HOST_GUESS" ]]; then
    step "detected public hostname: $R2_HOST_GUESS"
    R2_PUBLIC_HOST="$R2_HOST_GUESS"
  else
    ask R2_PUBLIC_HOST "Paste the r2.dev hostname (pub-....r2.dev):"
  fi
  write_env R2_PUBLIC_HOST "$R2_PUBLIC_HOST"
  SKIPPED+=("point R2_PUBLIC_HOST at a custom domain once the project has a domain (ADR 0011)")
  pause "Press Enter to continue."
else
  stage "Attach the custom domain to the bucket"
  say "Serving images from our own hostname is what puts the Cloudflare CDN cache"
  say "in front of them, and what keeps the prerendered listing cheap on the"
  say "metered connections most adopters are browsing from."
  ask R2_PUBLIC_HOST "Public image hostname [Enter for media.$PAWSTER_DOMAIN]:"
  [[ -z "$R2_PUBLIC_HOST" ]] && R2_PUBLIC_HOST="media.$PAWSTER_DOMAIN"
  write_env R2_PUBLIC_HOST "$R2_PUBLIC_HOST"
  printf '\n'
  say "Attaching it by CLI. Wrangler may ask you to confirm the DNS record."
  # Run directly rather than through capture(): this command can prompt, and
  # capture() redirects stdout to a file, which would hide the prompt and hang.
  if wr r2 bucket domain add "$R2_BUCKET" --domain "$R2_PUBLIC_HOST" --zone-id "$CLOUDFLARE_ZONE_ID"; then
    step "custom domain attached."
  else
    warn "the CLI could not attach it. Do it in the dashboard instead:"
    note "R2 object storage -> $R2_BUCKET -> Settings -> Custom Domains -> Add"
    open_url "https://dash.cloudflare.com/?to=/:account/r2/default/buckets/$R2_BUCKET/settings"
    pause "Press Enter once the custom domain shows as connected."
  fi
  printf '\n'
  say "Do NOT enable the r2.dev development URL. It is rate-limited and not"
  say "meant for production, and the custom domain replaces it."
  printf '\n'
  say "Checking the hostname resolves:"
  R2_HOST_DNS=$(dig +short "$R2_PUBLIC_HOST" 2>/dev/null || true)
  if [[ -n "$R2_HOST_DNS" ]]; then
    printf '%s\n' "$R2_HOST_DNS" | sed 's/^/    /'
    step "$R2_PUBLIC_HOST resolves."
  else
    warn "not resolving yet — give it a few minutes."
    SKIPPED+=("re-check: dig +short $R2_PUBLIC_HOST resolves")
  fi
  pause "Press Enter to continue."
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "The admin inbox"
say "ADR 0002 gave the platform no admin accounts at all: every verification"
say "decision arrives as a signed link in one mailbox, so this address *is* the"
say "admin credential. It is also where ADR 0012's 6 GB storage alarm lands,"
say "and it is the recipient the next stage's budget alert wants."
printf '\n'
warn "Use an address you would notice losing control of. It is published"
warn "nowhere, but whoever holds it can verify or revoke any shelter."
ask PAWSTER_ADMIN_EMAIL "Admin inbox address:"
write_env PAWSTER_ADMIN_EMAIL "$PAWSTER_ADMIN_EMAIL"
pause "Press Enter to continue."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Budget alert on usage-based spend"
say "ADR 0006's asymmetry: Workers, D1 and Queues fail closed when the free"
say "tier runs out. R2 bills. So R2 is the one component that can turn a \$0"
say "project into an invoice, and it needs a backstop."
printf '\n'
warn "A budget alert is informational only. Cloudflare's docs: 'Budget alerts"
warn "are informational only. They do not pause or cap usage.'"
note "So this is the backstop, not the control. The control is the"
note "application-enforced photo-count and byte caps ADR 0006 specifies."
printf '\n'
note "Availability: 'Budget alerts are available to Pay-as-you-go accounts"
note "only.' Activating R2 in stage 4 is normally what makes the account"
note "pay-as-you-go. Since 2026-06-15 eligible accounts also get an automatic"
note "\$10 budget alert each billing cycle, so you may find one already there."
printf '\n'
open_url "https://dash.cloudflare.com/?to=/:account/billing/billable-usage"
step "Manage Account -> Billing -> Billable Usage -> Create budget alert."
step "Name it something like 'R2 spend warning', set a low threshold, and add"
step "your email as a recipient."
ask R2_BUDGET_ALERT "What did you set, or why couldn't you? (e.g. '\$1 to me' / 'not offered'):"
write_env R2_BUDGET_ALERT "$R2_BUDGET_ALERT"
pause "Press Enter to continue."

# ── 10 ────────────────────────────────────────────────────────────────────
if (( ! NO_DOMAIN )); then
  stage "Images transformations on a Free zone (observation only)"
  say "Issue #12 established that transformations are documented as available on"
  say "Free plans, correcting an older belief that they were gated behind Pro."
  say "Nobody has confirmed it on a real Free zone, so confirm it now."
  printf '\n'
  note "This is not load-bearing: ADR 0007 pre-generates every derivative at"
  note "upload time, so no transformation runs when an adopter loads a page. We"
  note "are recording a fact, not unblocking anything."
  open_url "https://dash.cloudflare.com/?to=/:account/$PAWSTER_DOMAIN/images"
  step "Look for Images -> Transformations and try enabling it for this zone."
  ask IMAGES_TRANSFORMATIONS_ON_FREE "Did transformations enable on the Free zone? (yes / no / notes):"
  write_env IMAGES_TRANSFORMATIONS_ON_FREE "$IMAGES_TRANSFORMATIONS_ON_FREE"
  pause "Press Enter to continue."
fi

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Create the D1 database"
say "D1 holds shelters, animals, subscriptions and the digest sent-set. ADR"
say "0006 chose it because the dataset is small and structured, D1 supports"
say "FTS5, and SQLite runs in CI from a file with no network and no credentials."
printf '\n'
note "Free-plan ceiling worth remembering: 500 MB per database."
ask D1_DATABASE_NAME "Database name [Enter for pawster]:"
[[ -z "$D1_DATABASE_NAME" ]] && D1_DATABASE_NAME="pawster"
write_env D1_DATABASE_NAME "$D1_DATABASE_NAME"
printf '\n'
D1_DATABASE_ID=""
if capture wr d1 create "$D1_DATABASE_NAME"; then
  D1_DATABASE_ID=$(printf '%s\n' "$CAPTURED" \
    | grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' \
    | head -n1 || true)
else
  warn "create failed. If the database already exists, run 'wr d1 list' and"
  warn "copy its id below."
fi
if [[ -n "$D1_DATABASE_ID" ]]; then
  step "detected database id: $D1_DATABASE_ID"
  write_env D1_DATABASE_ID "$D1_DATABASE_ID"
else
  ask D1_DATABASE_ID "Paste the database id (uuid):"
  write_env D1_DATABASE_ID "$D1_DATABASE_ID"
fi
pause "Press Enter to continue."

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Create the Queue"
say "ADR 0006's digest path is Cron Trigger -> Queue -> consumer. Queues is on"
say "the Workers Free plan at 10,000 operations/day, which is why QStash was"
say "dropped and there is no third-party scheduler to provision."
printf '\n'
note "Messages are retained 24 hours on Free — the free-tier maximum — and are"
note "deliberately not the source of truth. The per-subscription sent-set in D1"
note "is; a message lost to retention is picked up by the next run (ADR 0009)."
ask QUEUE_NAME "Queue name [Enter for pawster-digest]:"
[[ -z "$QUEUE_NAME" ]] && QUEUE_NAME="pawster-digest"
write_env QUEUE_NAME "$QUEUE_NAME"
printf '\n'
if capture wr queues create "$QUEUE_NAME" --message-retention-period-secs 86400; then
  step "queue created with the 24-hour free-tier retention maximum."
else
  warn "create failed. If the queue already exists, that is fine."
fi
printf '\n'
say "ADR 0009 puts retry at two levels: Queues redelivers the enqueue message"
say "and then dead-letters it, and the dead-letter queue's consumer is what"
say "pings Healthchecks' /fail endpoint. That needs a second, real queue."
ask QUEUE_DLQ_NAME "Dead-letter queue name [Enter for $QUEUE_NAME-dlq]:"
[[ -z "$QUEUE_DLQ_NAME" ]] && QUEUE_DLQ_NAME="$QUEUE_NAME-dlq"
write_env QUEUE_DLQ_NAME "$QUEUE_DLQ_NAME"
printf '\n'
if capture wr queues create "$QUEUE_DLQ_NAME" --message-retention-period-secs 86400; then
  step "dead-letter queue created."
else
  warn "create failed. If the queue already exists, that is fine."
fi
printf '\n'
note "Both consumer bindings come later, with the digest Worker, via"
note "'wrangler queues consumer add $QUEUE_NAME <worker>"
note "--dead-letter-queue $QUEUE_DLQ_NAME' — there is no Worker to bind yet."
SKIPPED+=("wire $QUEUE_DLQ_NAME as $QUEUE_NAME's dead-letter queue, once the digest Worker exists")
SKIPPED+=("point the $QUEUE_DLQ_NAME consumer at the Healthchecks /fail endpoint (ADR 0009)")
pause "Press Enter to continue."

# ── 13 ────────────────────────────────────────────────────────────────────
if (( ! NO_DOMAIN )); then
  stage "Resend: the account and the sending subdomain"
  say "Resend carries everything: shelter magic links, subscriber opt-ins,"
  say "confirmation nudges and the digest itself."
  printf '\n'
  warn "The ceiling that binds is 100 emails/day and 3,000/month on the"
  warn "transactional path. ADR 0009 budgets the digest at 100 minus 30, holding"
  warn "30 back so magic links and opt-ins always win, which is what makes the"
  warn "\$0 ceiling roughly 500 weekly subscribers rather than 1,000."
  printf '\n'
  say "Resend recommends a subdomain over the root domain, so that a deliverability"
  say "problem with bulk mail never contaminates the root domain's reputation."
  open_url "https://resend.com/domains"
  step "Create the account, then Add Domain."
  ask RESEND_SENDING_DOMAIN "Sending subdomain [Enter for mail.$PAWSTER_DOMAIN]:"
  [[ -z "$RESEND_SENDING_DOMAIN" ]] && RESEND_SENDING_DOMAIN="mail.$PAWSTER_DOMAIN"
  write_env RESEND_SENDING_DOMAIN "$RESEND_SENDING_DOMAIN"
  step "Add '$RESEND_SENDING_DOMAIN' as the domain in Resend."
  pause "Press Enter once Resend is showing you the DNS records."

  # ── 14 ────────────────────────────────────────────────────────────────────
  stage "Resend: the DNS records, in the Cloudflare zone"
  say "Resend generates the values per domain, so copy them from the page you"
  say "just opened. Three records, all on the sending subdomain:"
  printf '\n'
  step "MX    name 'send'                priority 10   value from Resend"
  step "TXT   name 'send'                SPF          value from Resend"
  step "TXT   name 'resend._domainkey'   DKIM         value from Resend"
  printf '\n'
  warn "Set every one of them to 'DNS only' — the grey cloud, not the orange one."
  note "Cloudflare's default is proxied, and a proxied DKIM record will not"
  note "verify. Resend's own Cloudflare guide is explicit: 'Confirm your proxy"
  note "settings are set to DNS Only on the record you are adding.'"
  printf '\n'
  note "Paste only the short name ('send', 'resend._domainkey') — Cloudflare"
  note "appends the zone for you, and pasting the full hostname double-suffixes it."
  printf '\n'
  say "Resend also offers a 'Sign in to Cloudflare' button that writes these"
  say "records for you over Domain Connect. If you use it, still go back and"
  say "check the proxy status on each record afterwards."
  open_url "https://dash.cloudflare.com/?to=/:account/$PAWSTER_DOMAIN/dns/records"
  pause "Press Enter once all three records are added, DNS only."
  printf '\n'
  say "Checking DKIM has propagated:"
  DKIM_DNS=$(dig +short TXT "resend._domainkey.$RESEND_SENDING_DOMAIN" 2>/dev/null || true)
  if [[ -n "$DKIM_DNS" ]]; then
    printf '%s\n' "$DKIM_DNS" | sed 's/^/    /'
    step "DKIM record is visible."
  else
    warn "not visible yet. Propagation is usually minutes; verification in"
    warn "Resend will stay pending until it is."
    SKIPPED+=("verify $RESEND_SENDING_DOMAIN in Resend once DKIM propagates")
  fi
  ask RESEND_DOMAIN_STATUS "Domain status in Resend right now (verified / pending):"
  write_env RESEND_DOMAIN_STATUS "$RESEND_DOMAIN_STATUS"
  pause "Press Enter to continue."
fi

# ── 15 ────────────────────────────────────────────────────────────────────
stage "Resend: the API key"
say "One key, used by both Workers and by CI."
open_url "https://resend.com/api-keys"
step "Create API Key. Give it 'Sending access' only — it never needs full"
step "access, and a sending-only key cannot delete your domains."
ask_secret RESEND_API_KEY "Paste the API key (hidden, starts re_):"
write_env RESEND_API_KEY "$RESEND_API_KEY"
set_secret RESEND_API_KEY "$RESEND_API_KEY"
if (( NO_DOMAIN )); then
  printf '\n'
  warn "In this phase the key can only send to this account own address."
  note "Use onboarding@resend.dev as the From address. That is enough to build"
  note "and test every email path end to end with yourself as the recipient -"
  note "shelter sign-in, confirmation, digest - but not to reach anyone else."
fi
printf '\n'
note "Also stored as a GitHub Actions secret, because CI needs it. It is not"
note "in the provisioning record — no secret goes on a public issue."
pause "Press Enter to continue."

# ── 16 ────────────────────────────────────────────────────────────────────
stage "Healthchecks.io: the digest dead-man's switch"
say "Nothing inside Cloudflare can tell us a Cron Trigger never fired — that is"
say "why ADR 0009 puts an external watchdog outside the platform entirely."
printf '\n'
say "The cadence is the detail most likely to be set wrong, so: the digest is"
say "WEEKLY per subscriber, but the Cron Trigger fires DAILY. Each subscriber"
say "carries a send day assigned at opt-in, so one weekly digest becomes seven"
say "bounded daily shards sharing a single trigger. ADR 0010 also hangs the"
say "retention purges off the same daily run."
printf '\n'
warn "So the check's schedule is DAILY, not weekly. A weekly window would miss"
warn "six consecutive dead runs before it ever complained."
note "ADR 0009 specifies one ping at completion of each daily run, with a"
note "two-hour grace."
printf '\n'
ask DIGEST_CRON_UTC "Daily run time, UTC cron [Enter for '0 11 * * *' = 07:00 in Venezuela]:"
[[ -z "$DIGEST_CRON_UTC" ]] && DIGEST_CRON_UTC="0 11 * * *"
write_env DIGEST_CRON_UTC "$DIGEST_CRON_UTC"
open_url "https://healthchecks.io/checks/add/"
step "Create the account, then add a check named 'pawster-digest-daily'."
step "Choose the 'Cron' schedule type, not 'Simple'."
step "Cron expression: $DIGEST_CRON_UTC     Server's time zone: UTC"
step "Grace time: 2 hours."
step "Then copy the check's ping URL."
ask_secret HEALTHCHECKS_PING_URL "Paste the ping URL (hidden — it is a capability):"
write_env HEALTHCHECKS_PING_URL "$HEALTHCHECKS_PING_URL"
note "Treated as a secret: anyone holding that URL can ping the check and make"
note "a dead digest look alive."
SKIPPED+=("wrangler secret put HEALTHCHECKS_PING_URL, once the digest Worker exists")
pause "Press Enter to continue."

# ── 17 ────────────────────────────────────────────────────────────────────
stage "The Do-Not-Contact pepper"
say "ADR 0010's one permanent secret. It keys the HMAC-SHA256 that fingerprints"
say "addresses which reported us as spam, so complainants are never mailed again"
say "while we store no address at all."
printf '\n'
warn "This secret must NEVER rotate, and losing it fails open, silently."
note "The entries it produces are one-way and cannot be re-derived. Regenerate"
note "the pepper and every Do-Not-Contact entry quietly stops matching, and the"
note "platform resumes mailing the people who complained — with no alarm"
note "anywhere. Treat it like a signing key, not like an API key: an API key"
note "can be reissued, this cannot."
printf '\n'
EXISTING_PEPPER=$(_existing PAWSTER_DNC_PEPPER || true)
if [[ -n "$EXISTING_PEPPER" ]]; then
  step "A pepper is already in $ENV_FILE. Keeping it — this is the one value"
  step "the wizard refuses to regenerate."
  PAWSTER_DNC_PEPPER="$EXISTING_PEPPER"
else
  PAWSTER_DNC_PEPPER=$(openssl rand -base64 32)
  step "Generated a fresh 32-byte pepper, locally. It is shown once, below."
  printf '\n'
  printf '      %s%s%s\n' "$BOLD" "$PAWSTER_DNC_PEPPER" "$RESET"
  printf '\n'
  write_env PAWSTER_DNC_PEPPER "$PAWSTER_DNC_PEPPER"
fi
printf '\n'
say "Put it in your password manager now, in an entry you would notice losing."
until confirm "Is the pepper backed up somewhere that is not this repo?"; do
  warn "Back it up before continuing — this is the unrecoverable one."
done
ask PAWSTER_DNC_PEPPER_BACKUP "Where is it backed up? (e.g. '1Password, Pawster vault'):"
write_env PAWSTER_DNC_PEPPER_BACKUP "$PAWSTER_DNC_PEPPER_BACKUP"
printf '\n'
say "Deriving ADR 0010's boot-time canary, so a wrong or missing pepper fails"
say "loudly at startup instead of silently at send time."
PAWSTER_DNC_CANARY=$(printf 'pawster-dnc-canary' \
  | openssl dgst -sha256 -hmac "$PAWSTER_DNC_PEPPER" -binary \
  | openssl base64)
write_env PAWSTER_DNC_CANARY "$PAWSTER_DNC_CANARY"
note "Derived as: printf 'pawster-dnc-canary' | openssl dgst -sha256 -hmac"
note "\$PEPPER -binary | openssl base64. The Worker must HMAC the same literal"
note "the same way; if the build session formats its HMAC input differently,"
note "regenerate this constant rather than adjusting the pepper."
note "Kept out of the provisioning record — it is a value derived from the"
note "pepper, and the record goes on a public issue."
SKIPPED+=("wrangler secret put PAWSTER_DNC_PEPPER, once the Worker exists")
pause "Press Enter to continue."

# ── 18 ────────────────────────────────────────────────────────────────────
stage "The link-signing key"
say "Every route into Pawster that carries no session is a signed link: a"
say "shelter confirming its animals (ADR 0008), a subscriber managing or"
say "unsubscribing (ADR 0010), the admin deciding a verification (ADR 0002)."
say "They share one signing key, and #18 asked for it to be generated here."
printf '\n'
note "Unlike the pepper, this key MAY be rotated. Rotating it strands every"
note "live link — a shelter's nudge, a subscriber's manage link — which is a"
note "loud and recoverable failure. The pepper's failure is silent. Do not"
note "store the two as though they carried the same risk."
printf '\n'
EXISTING_LINK_KEY=$(_existing PAWSTER_LINK_SIGNING_KEY || true)
if [[ -n "$EXISTING_LINK_KEY" ]]; then
  step "A key is already in $ENV_FILE. Keeping it, so live links keep working."
  PAWSTER_LINK_SIGNING_KEY="$EXISTING_LINK_KEY"
else
  PAWSTER_LINK_SIGNING_KEY=$(openssl rand -base64 32)
  step "Generated a fresh 32-byte key, locally."
  write_env PAWSTER_LINK_SIGNING_KEY "$PAWSTER_LINK_SIGNING_KEY"
fi
printf '\n'
note "Not printed and not recorded: the provisioning record is destined for a"
note "public issue. Read it out of $ENV_FILE if you need it."
SKIPPED+=("wrangler secret put PAWSTER_LINK_SIGNING_KEY, once the Worker exists")
pause "Press Enter to continue."

# ── 19 ────────────────────────────────────────────────────────────────────
stage "Cloudflare API token, and the CI secrets"
say "CI deploys the Workers and applies D1 migrations, so it needs a scoped"
say "token — never your global API key."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create Token -> Create Custom Token."
step "Grant exactly these, all at Account level:"
note "    Workers Scripts: Edit"
note "    Workers R2 Storage: Edit"
note "    D1: Edit"
note "    Queues: Edit"
note "    Account Settings: Read"
step "Scope 'Account Resources' to this account only, then create and copy it."
ask_secret CLOUDFLARE_API_TOKEN "Paste the API token (hidden):"
write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
set_secret CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
set_secret CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
printf '\n'
note "The account id is set as a secret rather than a variable purely so the"
note "workflow references stay uniform under secrets.*; it is not sensitive."
pause "Press Enter to continue."

# ── 20 ────────────────────────────────────────────────────────────────────
stage "Make the repository public"
say "The public repo is part of the portfolio surface ADR 0006 describes."
printf '\n'
warn "This is the one irreversible step here. Anyone can then read every"
warn "commit, including anything a past commit shouldn't have contained."
printf '\n'
say "Scanning history for an accidentally committed env file:"
# Assigned rather than piped into `grep -q`: under `pipefail` an early-exiting
# grep SIGPIPEs the upstream command, so the pipeline reports failure even on a
# match — which would invert this check on the one irreversible step.
ENV_IN_HISTORY=$(git log --all --name-only --pretty=format: -- '.env' '.dev.vars' 2>/dev/null | tr -d '[:space:]' || true)
if [[ -n "$ENV_IN_HISTORY" ]]; then
  warn "history contains .env or .dev.vars. Do NOT make this public until the"
  warn "history is cleaned and every exposed credential is rotated."
  SKIPPED+=("clean .env out of history, rotate credentials, then make the repo public")
else
  step "no env file in history."
  printf '\n'
  if confirm "Make this repository public now?"; then
    if gh repo edit --visibility public --accept-visibility-change-consequences; then
      step "repository is public."
      REPO_VISIBILITY="public"
    else
      warn "the visibility change failed; do it in the repo settings."
      SKIPPED+=("make the repository public")
      REPO_VISIBILITY="private (change failed)"
    fi
  else
    note "Left private. Nothing else depends on it."
    SKIPPED+=("make the repository public, when you are ready")
    REPO_VISIBILITY="private (deferred)"
  fi
fi
pause "Press Enter to write the provisioning record."

# ── 21 ────────────────────────────────────────────────────────────────────
stage "Write the provisioning record"
say "Everything captured, minus every secret, as a file you can paste onto"
say "issue #18 as its resolution comment."
mkdir -p "$(dirname "$RECORD")"
{
  printf '# Provisioning record\n\n'
  if (( NO_DOMAIN )); then
    printf 'Partially addresses [#18 Provision the stack accounts and the domain](https://github.com/sabucds/pawster/issues/18):\n'
    printf 'run with `--no-domain`, so the domain-dependent stages are outstanding.\n'
  else
    printf 'Resolves [#18 Provision the stack accounts and the domain](https://github.com/sabucds/pawster/issues/18).\n'
  fi
  printf 'Generated by `scripts/provision.sh` on %s.\n\n' "$(date -u '+%Y-%m-%d %H:%M UTC')"
  printf '## Facts later tickets depend on\n\n'
  printf '| Fact | Value |\n| --- | --- |\n'
  if (( NO_DOMAIN )); then
    printf '| Phase | domain-free prototype (`--no-domain`, ADR 0014) |\n'
    printf '| Zone / domain | none in this phase |\n'
  else
    printf '| Phase | full provisioning |\n'
    printf '| Zone / domain | `%s` |\n' "$PAWSTER_DOMAIN"
  fi
  printf '| Cloudflare account id | `%s` |\n' "$CLOUDFLARE_ACCOUNT_ID"
  if (( NO_DOMAIN )); then
    printf '| Cloudflare zone id | none in this phase |\n'
  else
    printf '| Cloudflare zone id | `%s` |\n' "$CLOUDFLARE_ZONE_ID"
  fi
  printf '| R2 bucket | `%s` |\n' "$R2_BUCKET"
  if (( NO_DOMAIN )); then
    printf '| R2 public hostname | `%s` (r2.dev, uncached - ADR 0014) |\n' "$R2_PUBLIC_HOST"
  else
    printf '| R2 public hostname | `%s` |\n' "$R2_PUBLIC_HOST"
  fi
  printf '| R2 originals bucket (never public) | `%s` |\n' "$R2_ORIGINALS_BUCKET"
  printf '| Originals lifecycle rule | %s |\n' "$R2_ORIGINALS_LIFECYCLE"
  printf '| D1 database name | `%s` |\n' "$D1_DATABASE_NAME"
  printf '| D1 database id | `%s` |\n' "$D1_DATABASE_ID"
  printf '| Queue name | `%s` |\n' "$QUEUE_NAME"
  printf '| Dead-letter queue | `%s` |\n' "$QUEUE_DLQ_NAME"
  printf '| Admin inbox (ADR 0002 credential) | `%s` |\n' "$PAWSTER_ADMIN_EMAIL"
  if (( NO_DOMAIN )); then
    printf '| Resend sending domain | none - sandbox `onboarding@resend.dev`, own inbox only |\n'
  else
    printf '| Resend sending domain | `%s` (%s) |\n' "$RESEND_SENDING_DOMAIN" "$RESEND_DOMAIN_STATUS"
  fi
  printf '| Digest cron (UTC) | `%s` |\n' "$DIGEST_CRON_UTC"
  printf '| Repository visibility | %s |\n' "${REPO_VISIBILITY:-unchanged}"
  printf '\n## Observations the ticket asked for\n\n'
  printf -- '- **Did R2 activation demand a card?** %s\n' "$R2_ACTIVATION_ASKED_FOR_CARD"
  printf -- '- **Did Images transformations enable on the Free zone?** %s\n' "$IMAGES_TRANSFORMATIONS_ON_FREE"
  printf -- '- **R2 budget alert:** %s\n' "$R2_BUDGET_ALERT"
  printf '\n## Where the credentials live\n\n'
  printf -- '- `.env` at the repo root, ignored by git: `RESEND_API_KEY`,\n'
  printf -- '  `CLOUDFLARE_API_TOKEN`, `HEALTHCHECKS_PING_URL`, `PAWSTER_DNC_PEPPER`,\n'
  printf -- '  `PAWSTER_DNC_CANARY`, `PAWSTER_LINK_SIGNING_KEY`.\n'
  printf -- '- GitHub Actions secrets: `CLOUDFLARE_API_TOKEN`, `CLOUDFLARE_ACCOUNT_ID`,\n'
  printf -- '  `RESEND_API_KEY`.\n'
  printf -- '- The Do-Not-Contact pepper is additionally backed up at: %s.\n' "$PAWSTER_DNC_PEPPER_BACKUP"
  printf -- '  It must never rotate; losing it fails open silently (ADR 0010).\n'
  printf -- '- The link-signing key may be rotated: doing so strands live links\n'
  printf -- '  (loud, recoverable) rather than failing open (silent).\n'
  printf '\n## Ceilings now live\n\n'
  printf -- '- Resend transactional: 100/day, 3,000/month. ADR 0009 budgets the digest\n'
  printf -- '  at `100 - 30`, so the $0 ceiling is ~500 weekly subscribers.\n'
  if (( NO_DOMAIN )); then
    printf -- '  Not reachable in this phase: without a verified domain the only\n'
    printf -- '  deliverable address is this account own, so the binding limit is\n'
    printf -- '  domain verification, not the quota.\n'
  fi
  printf -- '- R2: 10 GB-month, 1M Class A, 10M Class B, egress free. The only\n'
  printf -- '  component that bills instead of failing. ADR 0012 puts the lifetime\n'
  printf -- '  ceiling at ~9,500 animals, revised down from ~12,500.\n'
  printf -- '- Images: 5,000 transformations per calendar month, recurring. The\n'
  printf -- '  derivative set costs `2N + 2` per animal, so ~350-500 new animals\n'
  printf -- '  per month. Fails closed at error 9422, with no `onerror` fallback\n'
  printf -- '  for the binding (ADR 0012).\n'
  printf -- '- Queues: 10,000 operations/day; messages retained 24h on Free.\n'
  printf -- '- D1: 500 MB per database.\n'
  if (( NO_DOMAIN )); then
    printf '\n## Deferred by `--no-domain`\n\n'
    printf 'Four stages need a domain and its Cloudflare zone, and did not run:\n\n'
    printf -- '- **2** the domain, and its zone on Cloudflare\n'
    printf -- '- **10** Images transformations (observation only; needs a zone)\n'
    printf -- '- **13** the Resend sending subdomain\n'
    printf -- '- **14** the Resend DNS records (MX, SPF, DKIM)\n'
    printf '\nConsequence: Resend reaches only this account own address, so shelter\n'
    printf 'sign-in codes (ADR 0013), admin verification links (ADR 0002) and the\n'
    printf 'subscriber digest (ADR 0009) work for the operator alone. Onboarding a\n'
    printf 'second shelter, or one real subscriber, requires a domain.\n'
    printf '\nSee [ADR 0014](adr/0014-domain-free-prototype-phase.md).\n'
  fi
  printf '\n## Still to do by hand\n\n'
  if [[ -n "${SKIPPED[*]:-}" ]]; then
    for _s in "${SKIPPED[@]:-}"; do
      [[ -n "$_s" ]] && printf -- '- %s\n' "$_s"
    done
  else
    printf -- '- Nothing outstanding.\n'
  fi
  printf '\n> Secrets are deliberately absent from this record.\n'
} > "$RECORD"
step "wrote $RECORD"
printf '\n'
if (( NO_DOMAIN )); then
  say "Paste that file onto issue #18. Do NOT close it: the domain-dependent"
  say "stages are still outstanding."
  note "  gh issue comment 18 --body-file $RECORD"
else
  say "Paste that file onto issue #18, then close it:"
  note "  gh issue comment 18 --body-file $RECORD"
  note "  gh issue close 18"
fi
pause "Press Enter for the summary."

finish
