/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=./dist/server/wrangler.json --include-runtime=false ./worker-configuration.d.ts` (hash: d9393f7a52400648fe3797be7442115d)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/entry");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
